In [1]:
from cloudfiles import CloudFiles
from cloudvolume import CloudVolume
import numpy as np
from copy import deepcopy

/home/nkemnitz/zetta/zetta_utils/venv-3.11/lib/python3.11/site-packages/python_jsonschema_objects/__init__.py:113: UserWarning: Schema id not specified. Defaulting to 'self'
  warnings.warn("Schema id not specified. Defaulting to 'self'")


In [2]:
cf = CloudFiles("gs://zetta-research-nico/hippocampus/rigid_transforms_3x3_LMedS/")
import  numpy as np
z_offsets = list(reversed(np.unique([int(x.split('/')[0][1:]) for x in list(cf.list(prefix="z"))])))

In [1]:
skip_map = {
	"37": 33, "40": 38, "44": 42, "56": 54, "58": 56, "79": 67, "86": 84, "95": 91, "107": 105, "110": 108, "112": 110, "114": 112, "116": 114, "118": 116, "121": 118, "123": 121, "160": 158, "162": 160, "191": 189, "212": 208, "275": 271, "284": 282, "295": 288, "339": 337, "358": 356, "381": 376, "399": 397, "403": 401, "467": 465, "621": 617, "643": 637, "700": 698, "803": 773, "825": 823, "1204": 1202, "1300": 1298, "1325": 1323, "1328": 1325, "1356": 1350, "1361": 1359, "1364": 1362, "1381": 1379, "1386": 1383, "1394": 1391, "1419": 1416, "1423": 1419, "1432": 1430, "1434": 1432, "1446": 1439, "1448": 1446, "1451": 1448, "1464": 1451, "1479": 1464, "1501": 1479, "1505": 1503, "1531": 1529, "1557": 1550, "1560": 1558, "1564": 1560, "1575": 1564, "1578": 1575, "1585": 1578, "1594": 1585, "1598": 1594, "1641": 1639, "1730": 1720, "1739": 1730, "1750": 1745, "1781": 1751, "1787": 1785, "1789": 1787, "1791": 1789, "1800": 1792, "1802": 1800, "1819": 1817, "1927": 1925, "1997": 1995, "2021": 2019, "2031": 2029, "2166": 2164, "2175": 2173, "2182": 2180, "2198": 2196, "2740": 2236, "2754": 2752, "2764": 2762, "2812": 2810, "2826": 2824, "2836": 2834, "2876": 2874, "2880": 2877, "2882": 2880, "2894": 2892, "2956": 2954, "2958": 2956, "3049": 3041, "3183": 3181, "3210": 3208, "3212": 3210, "3275": 3273, "3306": 3304, "3313": 3311, "3375": 3373, "3452": 3450, "3635": 3633, "3726": 3723, "3737": 3735, "3773": 3771, "3813": 3811, "3876": 3874, "3907": 3904
}
missing_z = []
for k,v in skip_map.items():
	for i in range(v+1, int(k)):
		missing_z.append(i)
missing_z

[34,
 35,
 36,
 39,
 43,
 55,
 57,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 85,
 92,
 93,
 94,
 106,
 109,
 111,
 113,
 115,
 117,
 119,
 120,
 122,
 159,
 161,
 190,
 209,
 210,
 211,
 272,
 273,
 274,
 283,
 289,
 290,
 291,
 292,
 293,
 294,
 338,
 357,
 377,
 378,
 379,
 380,
 398,
 402,
 466,
 618,
 619,
 620,
 638,
 639,
 640,
 641,
 642,
 699,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 824,
 1203,
 1299,
 1324,
 1326,
 1327,
 1351,
 1352,
 1353,
 1354,
 1355,
 1360,
 1363,
 1380,
 1384,
 1385,
 1392,
 1393,
 1417,
 1418,
 1420,
 1421,
 1422,
 1431,
 1433,
 1440,
 1441,
 1442,
 1443,
 1444,
 1445,
 1447,
 1449,
 1450,
 1452,
 1453,
 1454,
 1455,
 1456,
 1457,
 1458,
 1459,
 1460,
 1461,
 1462,
 1463,
 1465,
 1466,
 1467,
 1468,
 1469,
 1470,
 1471,
 1472,
 1473,
 1474,
 1475,
 1476,
 1477,
 1478,
 1480,
 1481,
 1482,
 1483,
 1484,
 148

In [3]:

z_cv = dict()
for z_offset in z_offsets:
    z_cv[z_offset] = CloudVolume(f"gs://zetta-research-nico/hippocampus/rigid_transforms_3x3_LMedS/z{z_offset}", fill_missing=True, progress=False)

rigid_rel = z_cv[-1][:,:,24:3994]


In [52]:

for z_offset in z_offsets[1:]:
    empty_z = np.where(np.sum(rigid_rel, axis=(0,1)) == 0)[0]
    print(len(empty_z), "missing z")
    for z in empty_z:
        if z in range(2214,2715):
            continue
        rigid_rel[:,:,z] = z_cv[z_offset][:,:,z+24].reshape(2,3,1)


0 missing z
0 missing z
0 missing z
0 missing z
0 missing z
0 missing z
0 missing z
0 missing z
0 missing z
0 missing z
0 missing z
0 missing z
0 missing z
0 missing z
0 missing z
0 missing z


In [82]:
###################################
# Combine rigid transformations estimates from z-1 and z-2 to get
# uninterrupted chain of relative rigid transformations
###################################

# IDENTITY = np.eye(2, 3, order='F').reshape(2,3,1,1)

# # Remaining gaps (likely empty section) are filled with identity
# rigid_rel[:,:,np.where(np.sum(rigid_rel, axis=(0,1)) == 0)[0]] = IDENTITY

# # Also need to expand the 2x3 rigid transformation to 3x3
# new_row = np.array([0, 0, 1]).reshape(1, 3, 1, 1)
# new_row_repeated = np.tile(new_row, (1, 1, rigid_rel.shape[2], 1))
# rigid_rel = np.vstack((rigid_rel, new_row_repeated), dtype=np.float64)

# Start relative determined by calculating absolute transformations first
# and picking section close to zero rotation (z=2165).
# Translation is just to push everything a bit more into the center
rigid_rel[:,:,0,0] = np.array(
    [[ 0.99796528,  0.06370474, 0.  ],
     [ -0.06370474,  0.99796528, 0.  ],
     [ 0.        ,  0.        , 1.  ]]
)

In [57]:
for z in range(rigid_rel.shape[2]):
    if z+24 not in missing_z and (rigid_rel[:2,:,z:z+1,:] == IDENTITY).all():
        print(z+24)

In [62]:
# Jump between 2236 and 2740 was too big to estimate automatically
rigid_rel[:,:,2740-24,0][:2,:3] = np.array(
    [[ 0.99995756, 0.00921211, 0.01358774 ],
     [-0.00921211, 0.99995756, 0.06229581 ]]
)

rigid_rel[:,:,1300-24,0][:2,:3] = np.array(
    [[ 0.97187746, -0.23548725, 0.06326449 ],
     [ 0.23548725, 0.97187746, -0.05125397 ]]
)

rigid_rel[:,:,1651-24,0][:2,:3] = np.array(
    [[ 0.99982774, 0.01855904, -0.00104252 ],
     [-0.01855904, 0.99982774, 0.13468754 ]]
)

rigid_rel[:,:,3298-24,0][:2,:3] = np.array(
    [[ 0.9998563, 0.01695335, -0.07846532 ],
     [-0.01695335, 0.9998563, 0.00165477 ]]
)

rigid_rel[:,:,3299-24,0][:2,:3] = np.array(
    [[ 9.9999982e-01, -4.9370364e-04, 1.7592669e-02 ],
     [ 4.9370364e-04, 9.9999982e-01, -8.2359403e-02 ]]
)

rigid_rel[:,:,889-24,0][:2,:3] = np.array(
    [[ 0.99920726, 0.03981131, 0.02034556 ],
     [ -0.03981131, 0.99920726, 0.12582526 ]]
)

rigid_rel[:,:,2826-24,0][:2,:3] = np.array(
    [[ 9.9998736e-01, 5.0276816e-03, 9.2865527e-04 ],
     [ -5.0276816e-03, 9.9998736e-01, 4.1489005e-03 ]]
)


rigid_rel[:,:,1346-24,0][:2,:3]

array([[ 0.99982244,  0.01884258,  0.02210818],
       [-0.01884258,  0.99982244, -0.02331861]])

In [83]:
#####################################
# Compute absolute rigid transformations
#####################################

# Compute the absolute transformations
absolute_transforms_fwd = [rigid_rel[:, :, 0].squeeze()]
for z in range(1, rigid_rel.shape[2]):
    absolute_transform = np.matmul(absolute_transforms_fwd[-1], rigid_rel[:, :, z].squeeze())
    absolute_transforms_fwd.append(absolute_transform)

for z in range(len(absolute_transforms_fwd)):
    absolute_transforms_fwd[z] = np.linalg.inv(absolute_transforms_fwd[z])



In [84]:
np.array(absolute_transforms_fwd)[102], np.array(absolute_transforms_fwd)[1237], np.array(absolute_transforms_fwd)[2237], np.array(absolute_transforms_fwd)[2740], np.array(absolute_transforms_fwd)[3540]
# len(absolute_transforms_fwd)

(array([[ 0.99453282, -0.10445639,  0.03902714],
        [ 0.10445639,  0.99453282,  0.02625121],
        [ 0.        ,  0.        ,  1.        ]]),
 array([[ 0.99993725,  0.01143276,  0.05844228],
        [-0.01143276,  0.99993725,  0.02980294],
        [ 0.        ,  0.        ,  1.        ]]),
 array([[ 1.00000000e+00, -3.81405223e-09, -3.57061000e-03],
        [ 3.81405223e-09,  1.00000000e+00,  3.32710725e-03],
        [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]]),
 array([[ 0.99991668,  0.01292101, -0.03308554],
        [-0.01292101,  0.99991668, -0.04775682],
        [ 0.        ,  0.        ,  1.        ]]),
 array([[ 0.9962845 ,  0.08612887,  0.03077984],
        [-0.08612887,  0.9962845 ,  0.06720478],
        [ 0.        ,  0.        ,  1.        ]]))

In [86]:
absolute_cv = CloudVolume("gs://zetta-research-nico/hippocampus/rigid_transforms_3x3_LMedS/absolute", delete_black_uploads=True, info=deepcopy(z_cv[-1].info), fill_missing=True)
absolute_cv.commit_info()
absolute_cv[:,:,:,0] = np.array(absolute_transforms_fwd)[:, :2, :3].transpose(1, 2, 0).astype(np.float32)


Uploading: 100%|██████████| 3970/3970 [00:43<00:00, 91.41it/s] 


In [85]:
np.median(np.array([x[1,0] for x in np.array(absolute_transforms_fwd)]))
# np.median(np.array(absolute_transforms_fwd)[:, :2, :3][0,0])

3.814052228013215e-09

In [3]:
absolute_cv = CloudVolume("gs://zetta-research-nico/hippocampus/rigid_transforms_3x3_LMedS/absolute", delete_black_uploads=True, fill_missing=True)
# pairwise_aff_cv = CloudVolume("gs://zetta-research-nico/hippocampus/affine_w_scale/transform_LMedS", delete_black_uploads=True, fill_missing=True)

In [4]:
# matrices = absolute_cv[:,:,:,:]
affine_matrices = pairwise_aff_cv[:,:,:,:]

Downloading:  34%|███▎      | 1338/3970 [00:18<00:35, 73.29it/s] 


KeyboardInterrupt: 

In [126]:
# matrices[:,:,1300-24]

x = []
y = []
for z in range(affine_matrices.shape[2]):
    U, S, Vh = np.linalg.svd(affine_matrices[:,:,z][:2,:2], full_matrices=True, compute_uv=True)
    if S[0] != 0:
        x.append(S[0][0])
    else:
        x.append(1.0)
    if S[1] != 0:
        y.append(S[1][0])
    else:
        y.append(1.0)

def moving_average(a, n=10):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

# np.linalg.svd(affine_matrices[:,:,1300-24][:2,:2], full_matrices=True, compute_uv=True)[1][1][0]
np.prod(x[1300-24:1300-24+20])
# y: 1.09
# x: 1.04
affine_matrices[:,:,1300-24]

VolumeCutout([[[ 0.9847318 ],
               [-0.2935958 ],
               [ 0.05365886]],

              [[ 0.31120548],
               [ 1.0819839 ],
               [-0.13995959]]], dtype=float32)

In [3]:
# # absolute_w_scale_cv = CloudVolume("gs://zetta-research-nico/hippocampus/rigid_transforms_3x3_LMedS/absolute_w_scale", delete_black_uploads=True, fill_missing=True)
# pairwise_aff_cv = CloudVolume("gs://zetta-research-nico/hippocampus/affine_w_scale/transform_LMedS", delete_black_uploads=True, fill_missing=True)
# scale = np.array([[[1.04], [0.0], [0.0]], [[0.0], [1.09], [0.0]], [[0.0], [0.0], [1.0]]]).squeeze()
# # scale @ np.vstack([affine_matrices[:,:,1300-24,0], np.array([0,0,1])])
# print(absolute_cv.bounds)

# for z in range(24, pairwise_aff_cv.bounds.maxpt[2]):
#     if z < 1301:
#         continue
#     mat = pairwise_aff_cv[:,:,z,:].squeeze()
#     if z < 1301:
#         new_mat = mat
#     else:
#         # new_mat = (np.vstack([mat, np.array([0,0,1])]) @ scale)[:2, :3] #rigid
#         new_mat = (scale @ np.vstack([mat, np.array([0,0,1])]))[:2, :3]
#     pairwise_aff_cv[:,:,z,:] = new_mat.reshape(2,3,1,1).astype(np.float32)


# absolute_w_scale_cv = CloudVolume("gs://zetta-research-nico/hippocampus/rigid_transforms_3x3_LMedS/absolute_w_scale", delete_black_uploads=True, fill_missing=True)
from cloudvolume.exceptions import EmptyVolumeException


pairwise_aff_cv = CloudVolume("gs://zetta-research-nico/hippocampus/affine_100th_w_scale/transform_LMedS", delete_black_uploads=True)
scale = np.array([[[1.04], [0.0], [0.0]], [[0.0], [1.09], [0.0]], [[0.0], [0.0], [1.0]]]).squeeze()

for z in range(24, pairwise_aff_cv.bounds.maxpt[2]):
    if z < 1301:
        continue
    try:
        mat = pairwise_aff_cv[:,:,z,:].squeeze()
    except EmptyVolumeException:
        continue
    if z < 1301:
        new_mat = mat
    else:
        # new_mat = (np.vstack([mat, np.array([0,0,1])]) @ scale)[:2, :3] #rigid
        new_mat = (scale @ np.vstack([mat, np.array([0,0,1])]))[:2, :3]
    pairwise_aff_cv[:,:,z,:] = new_mat.reshape(2,3,1,1).astype(np.float32)

Uploading: 100%|██████████| 1/1 [00:00<00:00,  6.10it/s]
